#!/usr/bin/env python3
"""Evaluate SWE-agent with ExpeL-extracted rules injected into system prompt.

This creates a SWE-agent config that injects a flat numbered rule list into
the system prompt (ExpeL's RULE_TEMPLATE style), then runs the experiment.

No graph structure, no retrieval — just static rules in the prompt.

Usage:
    # Generate the config only:
    uv run python scripts/baselines/expel_evaluate.py generate-config

    # Run full evaluation:
    uv run python scripts/baselines/expel_evaluate.py run --num-workers 2

    # Run with custom rules file:
    uv run python scripts/baselines/expel_evaluate.py run --rules-file data/baselines/expel_rules.json
"""

import json
import logging
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

import typer
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.baselines.expel_prompts import RULE_INJECTION_TEMPLATE

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

load_dotenv(PROJECT_ROOT / ".env")

app = typer.Typer(help="Evaluate SWE-agent with ExpeL flat rules baseline.")

# Default paths
DEFAULT_RULES_FILE = PROJECT_ROOT / "data" / "baselines" / "expel_rules.json"
DEFAULT_CONFIG_OUTPUT = PROJECT_ROOT / "configs" / "swe_agent_expel_baseline.yaml"
DEFAULT_RESULTS_DIR = PROJECT_ROOT / "results" / "live_experiment" / "expel_baseline"


def load_rules(rules_file: Path) -> list:
    """Load rules from the ExpeL extraction output."""
    with open(rules_file) as f:
        data = json.load(f)
    return data["rules"]


def format_rules_for_prompt(rules: list) -> str:
    """Format rules as a numbered list for injection into the system prompt."""
    lines = []
    for i, rule in enumerate(rules, 1):
        lines.append(f"{i}. {rule['text']}")
    return "\n".join(lines)


def generate_swe_agent_config(rules_text: str, output_path: Path) -> Path:
    """Generate a SWE-agent YAML config with ExpeL rules in system prompt.

    The rules are injected directly into the system_template so the agent
    sees them as static context (no tool calls needed).
    """
    # Format the full rule injection text
    rule_block = RULE_INJECTION_TEMPLATE.format(rules=rules_text)

    # Escape for YAML multiline string (|- block scalar)
    # No special escaping needed for |- blocks, but we need to indent properly
    rule_block_indented = "\n".join(f"      {line}" if line else "" for line in rule_block.split("\n"))

    config_content = f"""\
# SWE-agent config for ExpeL BASELINE (flat rules injected in system prompt)
# Auto-generated by scripts/baselines/expel_evaluate.py
# NO graph structure, NO retrieval — just static rules in prompt.

agent:
  type: default
  model:
    name: openai/claude-sonnet-4-20250514
    api_base: http://localhost:4000/v1
    api_key: $LITELLM_MASTER_KEY
    per_instance_cost_limit: 0
    max_output_tokens: 8192
    retry:
      retries: 3
      min_wait: 10.0
      max_wait: 180.0

  templates:
    system_template: |-
      You are a helpful assistant that can interact with a computer to solve tasks.

{rule_block_indented}
    instance_template: |-
      <uploaded_files>
      {{{{working_dir}}}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{{{working_dir}}}}. Consider the following PR description:

      <pr_description>
      {{{{problem_statement}}}}
      </pr_description>

      Can you help me implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met?
      I've already taken care of all changes to any of the test files described in the <pr_description>. This means you DON'T have to modify the testing logic or any of the tests in any way!
      Your task is to make the minimal changes to non-tests files in the {{{{working_dir}}}} directory to ensure the <pr_description> is satisfied.
      Follow these steps to resolve the issue:
      1. As a first step, it might be a good idea to find and read code relevant to the <pr_description>
      2. Create a script to reproduce the error and execute it with `python <filename.py>` using the bash tool, to confirm the error
      3. Edit the sourcecode of the repo to resolve the issue
      4. Rerun your reproduce script and confirm that the error is fixed!
      5. Think about edgecases and make sure your fix handles them as well
      Your thinking should be thorough and so it's fine if it's very long.
    next_step_template: |-
      OBSERVATION:
      {{{{observation}}}}
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.

  tools:
    env_variables:
      PAGER: cat
      MANPAGER: cat
      LESS: -R
      PIP_PROGRESS_BAR: 'off'
      TQDM_DISABLE: '1'
      GIT_PAGER: cat
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m
    registry_variables:
      USE_FILEMAP: 'true'
    execution_timeout: 180
    enable_bash_tool: true
    parse_function:
      type: function_calling

  history_processors: []
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config_content)

    return output_path


@app.command()
def generate_config(
    rules_file: Path = typer.Option(
        DEFAULT_RULES_FILE,
        help="Path to the ExpeL rules JSON file.",
    ),
    output: Path = typer.Option(
        DEFAULT_CONFIG_OUTPUT,
        help="Output path for the SWE-agent config YAML.",
    ),
):
    """Generate a SWE-agent config with ExpeL rules injected in system prompt."""
    if not rules_file.exists():
        typer.echo(f"Rules file not found: {rules_file}", err=True)
        typer.echo("Run 'uv run python scripts/baselines/expel_baseline.py extract' first.")
        raise typer.Exit(1)

    rules = load_rules(rules_file)
    rules_text = format_rules_for_prompt(rules)

    config_path = generate_swe_agent_config(rules_text, output)
    typer.echo(f"Generated SWE-agent config: {config_path}")
    typer.echo(f"  Rules injected: {len(rules)}")
    typer.echo(f"  Rules text length: {len(rules_text)} chars")


@app.command()
def run(
    rules_file: Path = typer.Option(
        DEFAULT_RULES_FILE,
        help="Path to the ExpeL rules JSON file.",
    ),
    config_output: Path = typer.Option(
        DEFAULT_CONFIG_OUTPUT,
        help="Path for generated SWE-agent config.",
    ),
    results_dir: Path = typer.Option(
        DEFAULT_RESULTS_DIR,
        help="Directory for experiment results.",
    ),
    max_problems: int = typer.Option(200, help="Max number of test problems."),
    num_workers: int = typer.Option(1, help="Number of parallel workers."),
    swe_bench_subset: str = typer.Option("verified", help="SWE-bench subset."),
    swe_bench_split: str = typer.Option("test", help="SWE-bench split."),
    seed: int = typer.Option(42, help="Random seed for problem selection."),
    dry_run: bool = typer.Option(False, help="Show commands without executing."),
):
    """Run SWE-agent evaluation with ExpeL rules baseline.

    This generates the config, then calls SWE-agent directly via
    `python -m sweagent run-batch` (same mechanism as run_real_swe_experiment.py).
    """
    import re as _re

    # Step 1: Generate config
    if not rules_file.exists():
        typer.echo(f"Rules file not found: {rules_file}", err=True)
        typer.echo("Run 'uv run python scripts/baselines/expel_baseline.py extract' first.")
        raise typer.Exit(1)

    rules = load_rules(rules_file)
    rules_text = format_rules_for_prompt(rules)
    config_path = generate_swe_agent_config(rules_text, config_output)
    logger.info(f"Generated config with {len(rules)} rules: {config_path}")

    # Step 2: Load test instance IDs (same logic as run_real_swe_experiment.py)
    verified_cache = PROJECT_ROOT / "results" / "live_experiment" / "verified_instance_ids.json"
    if verified_cache.exists():
        with open(verified_cache) as f:
            instance_ids = json.load(f)[:max_problems]
        logger.info(f"Loaded {len(instance_ids)} instance IDs from cache")
    else:
        typer.echo("Instance ID cache not found. Run run_real_swe_experiment.py first to generate it.")
        typer.echo(f"Expected: {verified_cache}")
        raise typer.Exit(1)

    # Step 3: Build SWE-agent command
    results_dir.mkdir(parents=True, exist_ok=True)

    escaped_ids = [_re.escape(iid) for iid in instance_ids]
    filter_pattern = "^(" + "|".join(escaped_ids) + ")$"

    cmd = [
        sys.executable, "-m", "sweagent",
        "run-batch",
        "--config", str(config_path),
        "--instances.type", "swe_bench",
        "--instances.subset", swe_bench_subset,
        "--instances.split", swe_bench_split,
        "--instances.filter", filter_pattern,
        "--output_dir", str(results_dir.resolve()),
        "--num_workers", str(num_workers),
        "--env_var_path", str(PROJECT_ROOT / ".env"),
    ]

    # On Linux, Docker containers need --add-host to resolve host.docker.internal
    if sys.platform == "linux":
        cmd += [
            "--instances.deployment.docker_args",
            '["--add-host=host.docker.internal:host-gateway", "--network=contextgraph_default"]',
        ]

    if dry_run:
        typer.echo(f"Would run:\n  {' '.join(cmd[:6])} ...")
        typer.echo(f"\nConfig: {config_path}")
        typer.echo(f"Output: {results_dir}")
        typer.echo(f"Instances: {len(instance_ids)}")
        typer.echo(f"\nRules ({len(rules)}):")
        for i, rule in enumerate(rules, 1):
            typer.echo(f"  {i}. [{rule['count']}] {rule['text']}")
        raise typer.Exit(0)

    logger.info(f"Running SWE-agent batch: {len(instance_ids)} instances, {num_workers} workers")
    logger.info(f"Config: {config_path}")
    logger.info(f"Output: {results_dir}")

    result = subprocess.run(cmd, cwd=str(PROJECT_ROOT))

    if result.returncode != 0:
        typer.echo(f"SWE-agent batch failed with return code {result.returncode}", err=True)
        raise typer.Exit(result.returncode)

    typer.echo(f"\nExperiment complete. Results in: {results_dir}")
    typer.echo("Run SWE-bench evaluation to verify results:")
    typer.echo(f"  uv run python scripts/run_evaluation.py --predictions-dir {results_dir}")


@app.command()
def show_config(
    rules_file: Path = typer.Option(
        DEFAULT_RULES_FILE,
        help="Path to the ExpeL rules JSON file.",
    ),
):
    """Preview the system prompt that would be injected."""
    if not rules_file.exists():
        typer.echo(f"Rules file not found: {rules_file}", err=True)
        raise typer.Exit(1)

    rules = load_rules(rules_file)
    rules_text = format_rules_for_prompt(rules)
    full_prompt = RULE_INJECTION_TEMPLATE.format(rules=rules_text)

    typer.echo("=" * 70)
    typer.echo("SYSTEM PROMPT (rule injection section)")
    typer.echo("=" * 70)
    typer.echo(full_prompt)
    typer.echo("=" * 70)
    typer.echo(f"\nTotal characters: {len(full_prompt)}")
    typer.echo(f"Estimated tokens: ~{len(full_prompt) // 4}")


if __name__ == "__main__":
    app()
